---

- name: Send notification message via Slack
  local_action:
    module: slack
    channel: "{{ channel | default('#ansible-notification') }}"
    color: "{{ color | default('normal') }}"
    icon_emoji: "{{ icon_emoji | default(':sunglasses:') }}"
    link_names: "{{ link_names | default(1) }}"
    msg: "{{ msg | default('message from ansible') }}"
    parse: "{{ parse | default('none') }}"
    token: "{{ slack.token }}"
    username: "{{ username | default('Ansible') }}"
